In [1]:
import numpy as np
num_List=np.array([1,4,5,6])
A=num_List*4
A

array([ 4, 16, 20, 24])

In [18]:
arr=np.array([1,5,7,8,9])
arr.size #5
arr.ndim #1
arr.dtype #dtype('int64')
arr.shape #(5,)
arr[3]#np.int64(8)
arr[1:5] #array([5, 7, 8, 9])
arr[0:5:2]array([1, 7, 9])

array([1, 7, 9])

In [29]:
arr2=np.array([[4,5,6],[8,10,12]])
arr2,arr2.shape,arr2.ndim,arr2.size,arr2.dtype
arr2[0] #array([4, 5, 6])
arr2[1] #array([ 8, 10, 12])


array([ 8, 10, 12])

In [32]:
arr3=np.array([4,7,8,10,12])
arr3+arr3

array([ 8, 14, 16, 20, 24])

In [33]:
arr3*10

array([ 40,  70,  80, 100, 120])

In [34]:
arr3-1

array([ 3,  6,  7,  9, 11])

In [35]:
arr3/2

array([2. , 3.5, 4. , 5. , 6. ])

In [36]:
arr3**3

array([  64,  343,  512, 1000, 1728])

In [37]:
arr4=np.ones([3,2])
arr4

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
arr5=np.ones((3,2))
arr5

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
num=np.random.rand()
num

0.7359365836848725

In [43]:
np.random.rand(5)

array([0.22756158, 0.88149739, 0.98609227, 0.56982354, 0.96117211])

In [2]:
np.random.randn()

-2.1347557069643064

In [4]:
np.random.randn(5)

array([-0.03621085, -1.22824397,  0.06725923, -0.14399784, -0.94064901])

In [5]:
np.random.randn(5,5)

array([[-0.92616643, -2.49902837, -0.7256176 , -0.70717314, -0.20104441],
       [-1.17923554,  1.074079  , -0.73696673,  1.62792408, -1.00659238],
       [ 0.76707968,  1.11854071,  1.79337036,  0.49364646, -1.34042087],
       [ 0.81084779, -1.48013025, -0.94422371,  0.77344818, -1.29975923],
       [ 0.36930069, -0.35522616, -0.33327353,  0.20492646, -1.13647449]])

In [6]:
#randint:generate a random number fro  0 to 100
np.random.randint(100)


78

In [7]:
np.random.randint(50,100)

98

In [8]:
np.random.randint(50,100,5)

array([63, 86, 68, 91, 79], dtype=int32)

In [9]:
np.random.randint(0,500)

83

In [10]:
np.random.randint(10,100,(5,5))

array([[17, 33, 10, 46, 22],
       [74, 42, 62, 99, 84],
       [55, 32, 67, 21, 92],
       [57, 20, 65, 36, 10],
       [32, 87, 76, 21, 52]], dtype=int32)

In [ ]:
#arange:generates the sequence of numbers
syntax:(start,end,step)


In [11]:
np.arange(0,10) # generates a sequence number fro 0to 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(20) # start value is always zero by default

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
np.arange(1,50,2) # step value by default is 1 step=2 skips one elemnts alternatively after 1st index.

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [17]:
#reshape function:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
data=np.arange(0,12).reshape(4,3)

In [20]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
data.max()

np.int64(11)

In [29]:
data.mean()

np.float64(5.5)

In [25]:
data.min()

np.int64(0)

In [26]:
data.std()

np.float64(3.452052529534663)

In [30]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
data==7

array([[False, False, False],
       [False, False, False],
       [False,  True, False],
       [False, False, False]])

In [33]:
# *** convert 1D to 2D data

ar=data.reshape(-1) # reshape(-1) -->converts n dim to 1D data

In [ ]:
# filtering the data

In [34]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
ar==7

array([False, False, False, False, False, False, False,  True, False,
       False, False, False])

In [36]:
ar>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [37]:
np.where(ar == 7)

(array([7]),)

In [38]:
np.where(ar >5)

(array([ 6,  7,  8,  9, 10, 11]),)

In [39]:
dt=np.array([100,200,300,400,500,600,700])

In [40]:
dt

array([100, 200, 300, 400, 500, 600, 700])

In [42]:
np.where(ar>3)


(array([ 4,  5,  6,  7,  8,  9, 10, 11]),)

In [ ]:
#2D indexing and slicing

In [43]:
np.where(dt>300)

(array([3, 4, 5, 6]),)

In [48]:
arr=np.array([[40,50,70,10],[20,120,80,90],[70,50,80,100],[170,200,190,140]])

In [49]:
arr

array([[ 40,  50,  70,  10],
       [ 20, 120,  80,  90],
       [ 70,  50,  80, 100],
       [170, 200, 190, 140]])

In [50]:
arr[0:2,1:3]

array([[ 50,  70],
       [120,  80]])

In [51]:
arr[1:,2:]

array([[ 80,  90],
       [ 80, 100],
       [190, 140]])

In [52]:
arr[:2,:3]

array([[ 40,  50,  70],
       [ 20, 120,  80]])

In [53]:
arr[::2,::2]

array([[40, 70],
       [70, 80]])

In [54]:
arr[1,1]

np.int64(120)

In [56]:
arr[3,0]

np.int64(170)

In [60]:
arr[1]=100

In [61]:
arr

array([[ 40,  50,  70,  10],
       [100, 100, 100, 100],
       [ 70,  50,  80, 100],
       [170, 200, 190, 140]])

In [65]:
len(arr)

4

In [63]:
for i in range(len(arr)): #0,1,2,3
    arr[i] =50

In [64]:
arr

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50]])