##Numpy:stands for numerical python which is used to perform numerical calculations
* numpy is used to handle the arrays and matrics
* numpy in python is library/package thart is used to work with arrays
* it is data structure used to store multiple values.

In [3]:
#import the module
import numpy as np
arr =np.array([])
print(arr)
print(type(arr))

[]
<class 'numpy.ndarray'>


In [3]:
#create numpy array to store values 2,3,4,5,61,2,4

arr1=np.array([ 2,3,4,5,61,2,4]);
print(arr1)
print(type(arr1))

[ 2  3  4  5 61  2  4]
<class 'numpy.ndarray'>


In [4]:
#create numpy array to store values such as blue,green,yellow,orange,white,black
colors =np.array(("blue","green","yellow","orange","white","black"))
print(colors)
print(type(colors))

['blue' 'green' 'yellow' 'orange' 'white' 'black']
<class 'numpy.ndarray'>


In [5]:
# how to create numpy array using list
list =[12,23,34,45,56,67,78,89]
arr=np.array(list)
print(arr)
print(type(arr))

[12 23 34 45 56 67 78 89]
<class 'numpy.ndarray'>


In [6]:
# how to create array using tuple

tuple=(101,102,103,104,105,107,106,108)
arr =np.array(tuple)
print(arr)
print(type(arr))

[101 102 103 104 105 107 106 108]
<class 'numpy.ndarray'>


In [8]:
#array doenst support with nsets and dict

sets={101,102,103,104,105,107,106,108}
arr=np.array(sets)
print(arr)
print(type(arr))

{101, 102, 103, 104, 105, 106, 107, 108}
<class 'numpy.ndarray'>


In [18]:
arr=np.array([1,2,3,4,5,6])
print(arr)
print("Dimentions of array:",arr.ndim)
print("number of elements:",arr.size)
print("data type of an array elements",arr.dtype)


[1 2 3 4 5 6]
Dimentions of array: 1
number of elements: 6
data type of an array elements int64


In [27]:
#2-d Array-- basically called as MATRICES

arr_2d=np.array([[1,2,3],[4,5,6],[5,6,7]])
print(arr_2d)
print("Dimension of matrix",arr_2d.ndim);
print("no of elments",arr_2d.size)
print("order of matrix",arr_2d.shape)

arr_2d1=np.array([[4,5,6,7],[8,9,1,2],[3,2,4,3],[9,2,1,4]])
print(arr_2d1)
print("Dimension of matrix",arr_2d1.ndim);
print("no of elments",arr_2d1.size)
print("order of matrix",arr_2d1.shape)

[[1 2 3]
 [4 5 6]
 [5 6 7]]
Dimension of matrix 2
no of elments 9
order of matrix (3, 3)
[[4 5 6 7]
 [8 9 1 2]
 [3 2 4 3]
 [9 2 1 4]]
Dimension of matrix 2
no of elments 16
order of matrix (4, 4)


In [32]:
#3D-array:

arr_3d =np.array([[[1,2,3],[3,4,5],[5,6,7]]])
print(arr_3d)
print("dimension:",arr_3d.ndim)
print("no of elements",arr_3d.size)
print("shape:",arr_3d.shape)

[[[1 2 3]
  [3 4 5]
  [5 6 7]]]
dimension: 3
no of elements 9
shape: (1, 3, 3)


# Built in functions to generate Numpy Array
#1.arange:used to generate evenly spaced values within a given interval
Note:End value is not included


In [40]:
#Generate the values from 0 to 14
np.arange(15)
#Generate the values from 0 to 30
np.arange(31)
# generate the values from 101 to 150
#arange (start,end)
np.arange(101,151)
#generate values from 400 to 480
np.arange(400,481)

array([400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412,
       413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425,
       426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438,
       439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451,
       452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464,
       465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477,
       478, 479, 480])

In [48]:
# generate first 10 even numbers
#arange(start,end,step)
np.arange(2,21,2)

#generate an array which includes 10 multiple of 5
np.arange(5,51,5)
#generate an array  10 multiple of 8
np.arange(8,81,8)#array([ 8, 16, 24, 32, 40, 48, 56, 64, 72, 80])

array([ 8, 16, 24, 32, 40, 48, 56, 64, 72, 80])

In [51]:
#ones:returns of array with  of all ones
# return 1-D array with 3 elements as 1
np.ones(3)
# return 1-D array with 10 elements as 1
np.ones(10) #array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])





array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
#create a unit matrix of order (2,2)
np.ones((2,2))

#create a unit matrix of order (5,3)
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
#zeros:
# create 1D-array with 5 elements as zeros
np.zeros(5)
#create 2D array or order(3,3)
# np.zeros(3)
#or
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [64]:
# create (2,2) identity matrix
np.eye(2)

#create (3,3) identity matrix

# np.eye(3,3)
# or
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
#create (4,3) identity matrix
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [75]:
#full matrix --used to generatr array with same elements
# works only for 2D array
#create (2,2) with all the elements as 10
np.full((2,2),10)

#create (4,3) with all the elemnts as 20
np.full((4,3),20)

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

In [80]:
#linspace-used to generate linearly spaced values
#generate linearly spaced values between 1 to 5
np.linspace(1,5)
#generate  10 equaly spaced values between 1 to 100
np.linspace(1,100, num=10,retstep=True)
# to find the difference between  two numbers we use retstep=True i.e =11
#generate the 10 numbers between 1 to 1000 and find the difference
np.linspace(1,1000,num=10,retstep=True)

(array([   1.,  112.,  223.,  334.,  445.,  556.,  667.,  778.,  889.,
        1000.]),
 np.float64(111.0))

In [5]:
# Random-to create array with random numbers
#randint--to generate an random integers for given interval

# create an array which includes 10 random integers between 1 to 100

np.random.randint(1,100,10)

array([64, 71, 80,  2, 47, 35, 43,  1, 47, 22], dtype=int32)

In [7]:
# generate an array which includes 5 random integers between 1 to 1000
np.random.randint(1,1000,5)

array([ 64, 506, 162, 116, 616], dtype=int32)

In [8]:
#creat a 2d array of order (2,2) which includes random integers between 20 to 60
np.random.randint(20,60,size=(2,2))

array([[49, 58],
       [48, 21]], dtype=int32)

In [10]:
#create 2d array of order(2,3) which include random integers netween 2,200
np.random.randint(2,200,size=(2,3))

array([[195, 153, 167],
       [ 97, 154,  36]], dtype=int32)

In [11]:
# rand:it generate random values between  range 0 to 1

#generate the 10 random values between 0 to 1

np.random.rand(10)


array([0.47762298, 0.9653861 , 0.48269549, 0.08314864, 0.67487269,
       0.74143137, 0.70935151, 0.04162886, 0.37347059, 0.46694847])

In [12]:
#generate the 100 random values between 0 to 1
np.random.rand(100)

array([0.62646677, 0.00452314, 0.68399861, 0.31762655, 0.61429373,
       0.21612794, 0.96281255, 0.68860433, 0.20979174, 0.78554137,
       0.47910419, 0.32676683, 0.07912163, 0.7176875 , 0.70863494,
       0.59135167, 0.11716671, 0.63948903, 0.58778466, 0.90865012,
       0.9100496 , 0.6720597 , 0.96624517, 0.44559969, 0.04583872,
       0.03944063, 0.99440665, 0.1819662 , 0.41891267, 0.0118161 ,
       0.49531008, 0.50360787, 0.25352195, 0.48862355, 0.17546458,
       0.34634728, 0.44076202, 0.41753069, 0.29904095, 0.81678397,
       0.33395142, 0.34953469, 0.88296665, 0.2819525 , 0.75258793,
       0.36512456, 0.76437956, 0.5390518 , 0.26128894, 0.86512999,
       0.06319589, 0.99210277, 0.51128332, 0.60767959, 0.8131573 ,
       0.95620484, 0.20417839, 0.31579801, 0.43254023, 0.56756105,
       0.6981253 , 0.38527419, 0.3344807 , 0.63288978, 0.65820743,
       0.13057153, 0.48140729, 0.75977742, 0.67390643, 0.13639443,
       0.42095886, 0.45841799, 0.26538764, 0.91891014, 0.67299

In [14]:
# create a 2d array of order (4,4) with random numbers between 0 to 1
np.random.rand(4,4)
#create a matrix of order (7,3) which includes numbers between 0 to 1
np.random.rand(7,3)

array([[0.14459934, 0.82760417, 0.0120169 ],
       [0.08732843, 0.52337199, 0.88222693],
       [0.67128944, 0.54524236, 0.69683561],
       [0.15585168, 0.10402547, 0.92251057],
       [0.24379316, 0.72381829, 0.9542357 ],
       [0.20440395, 0.64696355, 0.23136686],
       [0.22066962, 0.14640708, 0.09906963]])

In [17]:
#randn:it is used to generate the random numbers from normal distribution with in a range [-3,3]
#generate 10 the random numbers from normal distribution
np.random.randn(10)

array([ 0.53953994, -1.6247534 , -0.41945318,  0.08409625,  0.46783538,
       -0.83582178, -1.31269144, -0.71371767, -0.24840852, -1.11172123])

In [18]:
#create 2D array of order (5,5) which includes  normal distribution values
np.random.randn(5,5)

array([[-1.52793957,  0.63087463,  0.28844924,  0.95142518, -0.24306927],
       [-1.17192374, -1.37395288, -1.24280072,  0.12014607,  0.32669135],
       [-1.34413416,  0.34440426, -0.8641824 , -0.39539075,  0.32573328],
       [ 2.30859943,  0.51798252,  0.28304746, -0.70898501,  1.75221864],
       [ 0.0493209 ,  1.61708874,  0.99314535,  0.19625669,  3.09952366]])

In [20]:
#create 10 random integers between 1 to 10000
arr=np.random.randint(1,10000,10)
print(arr)

[9595 1802 2828 3240   49 5504 1072 8165  530 3023]


In [21]:
#maximum value:
np.max(arr)

np.int32(9595)

In [22]:
#argmax:it is used to get the index position of max value in an array
np.argmax(arr)

np.int64(0)

In [23]:
#minimum value
np.min(arr)

np.int32(49)

In [24]:
#argmin-index position of minimum value in an array
np.argmin(arr)

np.int64(4)

In [26]:
#indexing:positive indexing,-ve indexing
A=np.arange(20,30)
print(A)

[20 21 22 23 24 25 26 27 28 29]


In [30]:
#fetch 23
A[3]#23
#fetch 23,24,25
A[3:6]#[23, 24, 25]
 #how to reverse an array
A[::-1]#[29, 28, 27, 26, 25, 24, 23, 22, 21, 20]

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20])

In [39]:
##indexing with 2D array means extracting rows and columns
arr=np.array([[1,2,3],[4,5,6],[7,8,9]]);
print(arr)
#fetch first row
arr[[0]]
#fetch 3rd row
arr[[2]]
#fetching multiple rows or fetch first and second row
arr[[0,1]]
#fetch first n third row
arr[[0,2]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [7, 8, 9]])

In [43]:
#fetching the particular number in an 2D array
#fetch 4
arr[1][0]#4
#fetch 9
arr[2][2]#9 or arr[2,2]
#fetch 6
arr[1,2]#6

np.int64(6)

In [47]:
#fetching a column
#fetch first column
arr[:,0] #array([1, 4, 7])
arr[:,[0]] #gives in vertical we use []


#fetch 3rd column
arr[:,[2]]

array([[3],
       [6],
       [9]])

In [51]:
arr[:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [52]:
#fetch 1st and 3rd column
arr[:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [53]:
#fetch 1st and 2nd column
arr[:,[0,1]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [61]:
#Addition of 2 arrays
arr1 =np.array([10,20,30,40,50,60])
arr2=np.array([2,4,6,8,10,12])
arr1+arr2#array([12, 24, 36, 48, 60, 72])
#Substraction of 2 arrays
arr1-arr2#array([ 8, 16, 24, 32, 40, 48])
#Multiplication of 2 arrays
arr1*arr2#array([ 20,  80, 180, 320, 500, 720])
#Divide of 2 arrays
arr1/arr2#array([5., 5., 5., 5., 5., 5.])
#Division of 2 arrays
arr1%arr2
arr1+5#array([15, 25, 35, 45, 55, 65])


array([15, 25, 35, 45, 55, 65])